version: '3.8'

services:
  bot_findkzn:
    build: ./bot_findkzn
    container_name: bot_findkzn
    restart: always
    volumes:
      - bot_findkzn_sessions:/app/sessions
    stdin_open: true
    tty: true

  bot_oasismus:
    build: ./bot_oasismus
    container_name: bot_oasismus
    restart: always
    volumes:
      - bot_oasismus_sessions:/app/sessions
    stdin_open: true
    tty: true

volumes:
  bot_findkzn_sessions:
  bot_oasismus_sessions: